### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by AmmarMhd** [JaegerMa/MultiDeskBand#1]
When opening the project for the first time, VS 2015 complains that the project is not supported (see the shot).
![capture](https://cloud.githubusercontent.com/assets/4147076/19748492/af59aa88-9bea-11e6-954a-219e8cf1d449.PNG)
Where are 'LibDeskBand.dll' and 'LibHelper.dll' or at least the projects.
![capture2](https://cloud.githubusercontent.com/assets/4147076/19748510/d82074ce-9bea-11e6-9c18-51950420891f.PNG)

Please provide the entire solution

**Comment by JaegerMa** [comment]
See README
